from DimondPricePrediction.components.data_ingestion import DataIngestion
from DimondPricePrediction.components.data_transformation import DataTransformation
from DimondPricePrediction.components.model_trainer import ModelTrainer
import os
import sys
from DimondPricePrediction.logger import logging
from DimondPricePrediction.exception import CustomException
import pandas as pd
import numpy as np

obj=DataIngestion()
train_data_path,test_data_path=obj.initiate_data_ingestion()

data_transformation=DataTransformation()
train_arr,test_arr=data_transformation.initialize_data_transformation(train_data_path,test_data_path)

model_trainer_obj=ModelTrainer()
model_trainer_obj.initiate_model_training(train_arr,test_arr)